import { createElement } from '../renderer';

export interface ListeningPlayerCallbacks {
  onPlay: () => void;
  onReplay: () => void;
  onStop: () => void;
}

export interface ListeningPlayer {
  element: HTMLElement;
  setEnabled(enabled: boolean): void;
  updatePlayCount(count: number, maxPlays: number): void;
  destroy(): void;
}

export function createListeningPlayer(
  callbacks: ListeningPlayerCallbacks
): ListeningPlayer {
  const container = createElement('div', 'listening-player');

  const controls = createElement('div', 'listening-controls');

  const playButton = createElement('button', 'listening-btn listening-btn-play', 'Play');
  playButton.setAttribute('type', 'button');
  playButton.setAttribute('aria-label', 'Play audio');
  playButton.addEventListener('click', () => {
    if (!playButton.disabled) callbacks.onPlay();
  });

  const replayButton = createElement('button', 'listening-btn listening-btn-replay', 'Replay');
  replayButton.setAttribute('type', 'button');
  replayButton.setAttribute('aria-label', 'Replay audio');
  replayButton.disabled = true;
  replayButton.addEventListener('click', () => {
    if (!replayButton.disabled) callbacks.onReplay();
  });

  const stopButton = createElement('button', 'listening-btn listening-btn-stop', 'Stop');
  stopButton.setAttribute('type', 'button');
  stopButton.setAttribute('aria-label', 'Stop audio');
  stopButton.addEventListener('click', () => callbacks.onStop());

  controls.appendChild(playButton);
  controls.appendChild(replayButton);
  controls.appendChild(stopButton);

  const status = createElement('p', 'listening-status', 'Press Play to hear the audio');
  const note = createElement('p', 'listening-note', 'Audio is generated by your browser. Voice quality may vary by device.');

  container.appendChild(controls);
  container.appendChild(status);
  container.appendChild(note);

  function setEnabled(enabled: boolean) {
    playButton.disabled = !enabled;
  }

  function updatePlayCount(count: number, maxPlays: number) {
    if (count === 0) {
      status.textContent = 'Press Play to hear the audio';
      playButton.disabled = false;
      replayButton.disabled = true;
    } else if (count < maxPlays) {
      status.textContent = 'Audio played ' + count + ' of ' + maxPlays + ' times';
      playButton.disabled = true;
      replayButton.disabled = false;
    } else {
      status.textContent = 'Audio played ' + count + ' of ' + maxPlays + ' times (maximum reached)';
      playButton.disabled = true;
      replayButton.disabled = true;
    }
  }

  function destroy() {
    container.remove();
  }

  return {
    element: container,
    setEnabled,
    updatePlayCount,
    destroy
  };
}
